language: r
dist: trusty
bioc_required: true
warnings_are_errors: true
addons:
  apt:
    packages:
    - libudunits2-dev                     # units > ggforce > ggraph > patchwork > dynplot
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_hdf5
  - install_dynverse
cache:
  directories:
    - $HOME/R/Library
install:
 - use_dynverse_devel
 - install_cran devtools covr
 - install_withdeps
after_success:
 - echo Whyyyyyyy # R -e 'covr::codecov()'

jobs:
  include:
    - stage: prepare cache
      script:
        - echo Skip
      after_success:
        - echo Skip
    - stage: test
